### ISSUE TITLE
ERROR:CryticCompile:Contract has no public source code

### ISSUE THREAD

**Issue by acmLL** [Franklinliu/SpCon-Artifact#1]
Even with the command: docker run --rm liuyedocker/spcon-artifact:latest spcon --eth_address 0x2Ef27BF41236bD859a95209e17a43Fbd26851f92 (from the example you provide), I got this:

ERROR:CryticCompile:Contract has no public source code
total timecost: 3.805126428604126 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/staticAnalyzer.py", line 46, in analyze
    cc = CryticCompile(target=f"{network}:{address}", export_dir = export_dir, etherscan_export_dir = etherscan_export_dir, compile_remove_metadata=False, \
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.2.2-py3.8.egg/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.2.2-py3.8.egg/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.2.2-py3.8.egg/crytic_compile/platform/etherscan.py", line 256, in compile
    raise InvalidCompilation("Contract has no public source code: " + etherscan_url)
crytic_compile.platform.exceptions.InvalidCompilation: Contract has no public source code: https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0x2Ef27BF41236bD859a95209e17a43Fbd26851f92&apikey=URF6R5PGNZ7CT6TTBU7M8NH5V8WRISHIZZ

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/__main__.py", line 67, in main
    execute_command(args)
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/__main__.py", line 27, in execute_command
    contractName, contractAbi, reads, reads2, writes =  getRWofContract(address=args.eth_address)
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/staticAnalyzer.py", line 30, in getRWofContract
    contractName, contractAbi, reads, reads2,  writes = analyzer.analyze(address=address)
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/staticAnalyzer.py", line 77, in analyze
    exit(0)
  File "/usr/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

**Comment by Franklinliu** [comment]
Thanks for your comments. From the api result of https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0x2Ef27BF41236bD859a95209e17a43Fbd26851f92&apikey=URF6R5PGNZ7CT6TTBU7M8NH5V8WRISHIZZ, the used Etherscan API key inside SPCon is outdated. Please customize your own API key on Etherscan website and then replace the old one with it.

**Comment by acmLL** [comment]
Thanks, @Franklinliu ! I have cloned https://github.com/Franklinliu/SpCon-Artifact, updated the etherscan api key in the files staticAnalyzer.py and symExec.py, built the docker image locally (docker build . -t spcon-artifact) and run the provided command

docker run --rm spcon-artifact:latest spcon --eth_address 0x2Ef27BF41236bD859a95209e17a43Fbd26851f92

and got this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/__main__.py", line 67, in main
    execute_command(args)
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/__main__.py", line 29, in execute_command
    main_collecttransaction_history(address=args.eth_address, workdir=args.workspace, date = args.date)
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/query.py", line 64, in main_collecttransaction_history
    result2 = run_query(query_user_statistics, variables)  # Execute the query
  File "/usr/local/lib/python3.8/dist-packages/SpCon-0.1.0-py3.8.egg/spcon/query.py", line 23, in run_query
    print(request.json())
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

What can I do? Thanks!

**Comment by Franklinliu** [comment]
Could you check the content of resulting json to see the root cause?

**Comment by acmLL** [comment]
Hey, @Franklinliu . Sorry for my delay. Please find attached the json files generated. Thanks!
[jsons.zip](https://github.com/Franklinliu/SpCon-Artifact/files/11254666/jsons.zip)
